###
GET http://localhost:9003/api/users HTTP/1.1

###
POST http://localhost:9003/api/users HTTP/1.1
Content-Type: application/json

{

    "Name":"Devinson",
    "Surname":"DEsarrollador",
    "Cedula":"1017221241",
    "Username":"admin",
    "Email": "admin@gmail.com",
    "Phone": "3043850194",
    "Password":"admin123",
    "Rol":"admin"
     
}

###
PUT http://localhost:9003/users/api/6485407f6e9256dbec828b6b HTTP/1.1
Content-Type: application/json


{
    "Name":"Mauricio",
    "Surname":"Dorado",
    "Cedula":"124141",
    "Username":"Prueba Cuatro",
    "Email": "devinson@gmail.com",
    "phone": "3154567890",
    "Password":"r34523523",
    "Rol":"2" 
   
}

### 
DELETE http://localhost:9003/users/api/63922db755b5fe59c0d5e048 HTTP/1.1




###
POST http://localhost:9003/api/login HTTP/1.1
Content-Type: application/json

{
 "Username":"prueba uno",
 "Password":"lehr3456" 
}


###
GET http://localhost:9003/api/cites HTTP/1.1
Content-Type: application/json




###
POST http://localhost:9003/api/cites HTTP/1.1
Content-Type: application/json

{
    "Fecha":"2014-01-22",
    "Nombre":"Otra",
    "Apellidos":"Vez",
    "Email": "devinson22@gmail.com",
    "Phone": "3154567690"

}



###
GET http://localhost:9003/api/historias HTTP/1.1


###
POST http://localhost:9003/api/historias HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Historia",
    "Apellidos": "De",
    "Cedula": "12412415",
    "Edad": "40",
    "Etnia": "Negro",
    "Altura": "180",
    "Peso": "100",
    "Comoborbilidad": "Si",
    "Alergias": "Si",
    "Alcohol": "Si",
    "Tabaquismo": "Si",
    "Drogas": "Si",
    "Medicamentos": "Si"

}


###
POST http://localhost:9003/api/signup HTTP/1.1
Content-Type: application/json

{
    "Username":"Prueba 7070",
    "Email": "devinsodfh5745745gwdtetn@gmail.com",
    "Password":"hghegerg"

}


###
POST http://localhost:9003/api/signin HTTP/1.1
Content-Type: application/json

{
    "Email": "admin@gmail.com",
    "Password":"admin123"
}
  
